### ISSUE TITLE
Problem mit libvips

### ISSUE THREAD

**Issue by detafun** [ioBroker/ioBroker.iot#132]
Hallo,
hatte gehofft, das es mit dem neuen Update beseitigt wurde, Leider nein.
```
Update iot from @1.4.2 to @1.4.4
host.rock Adapter "system.adapter.iot.0" is stopped.
NPM version: 6.14.4
npm install iobroker.iot@1.4.4 --loglevel error --prefix "/opt/iobroker" (System call)
In file included from ../src/DeviceINQ.h:17,
                 from ../src/linux/BluetoothSerialPort.cc:13:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/linux/BluetoothSerialPort.cc: At global scope:
../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void
 void InitAll(Handle<Object> exports) {
              ^~~~~~
../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in this scope
../src/linux/BluetoothSerialPort.cc:18:14: note: suggested alternative: ‘rand_r’
 void InitAll(Handle<Object> exports) {
              ^~~~~~
              rand_r
../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token
 void InitAll(Handle<Object> exports) {
                           ^
../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in this scope
 void InitAll(Handle<Object> exports) {
                             ^~~~~~~
In file included from ../src/linux/BluetoothSerialPort.cc:12:
../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in this scope
 NODE_MODULE(BluetoothSerialPort, InitAll)
                                  ^~~~~~~
/home/iobroker/.cache/node-gyp/12.16.2/include/node/node.h:608:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(BluetoothSerialPort, InitAll)
 ^~~~~~~~~~~
make: *** [BluetoothSerialPort.target.mk:117: Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.192-rockchip64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/iobroker/node_modules/node-bluetooth
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
ERR! sharp Use with glibc 2.28 requires manual installation of libvips >= 8.9.1
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
In file included from ../src/common.cc:23:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.192-rockchip64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/sharp
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Update "system.adapter.iot.0"
upload [20] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/runtime-main.8b3eca34.js.map static/js/runtime-main.8b3eca34.js.map application/json
upload [19] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/runtime-main.8b3eca34.js static/js/runtime-main.8b3eca34.js application/javascript
upload [18] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/main.721d1c42.chunk.js.map static/js/main.721d1c42.chunk.js.map application/json
upload [17] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/main.721d1c42.chunk.js static/js/main.721d1c42.chunk.js application/javascript
upload [16] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.faa62e98.chunk.js.map static/js/2.faa62e98.chunk.js.map application/json
upload [15] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.faa62e98.chunk.js.LICENSE.txt static/js/2.faa62e98.chunk.js.LICENSE.txt text/plain
upload [14] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.faa62e98.chunk.js static/js/2.faa62e98.chunk.js application/javascript
upload [13] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/main.d4bed9c6.chunk.css.map static/css/main.d4bed9c6.chunk.css.map application/json
upload [12] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/main.d4bed9c6.chunk.css static/css/main.d4bed9c6.chunk.css text/css
upload [11] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/2.b1b16afe.chunk.css.map static/css/2.b1b16afe.chunk.css.map application/json
upload [10] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/2.b1b16afe.chunk.css static/css/2.b1b16afe.chunk.css text/css
upload [9] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/service-worker.js service-worker.js application/javascript
upload [8] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/precache-manifest.b5249c907f3acd0903d8c4d182d1dce1.js precache-manifest.b5249c907f3acd0903d8c4d182d1dce1.js application/javascript
upload [7] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/manifest.json manifest.json application/json
upload [6] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/iot.png iot.png image/png
upload [5] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/index_m.html index_m.html text/html
upload [4] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [3] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/blockly.js blockly.js application/javascript
upload [2] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/asset-manifest.json asset-manifest.json application/json
upload [1] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/alexalogo.png alexalogo.png image/png
upload [0] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/actions.js actions.js application/javascript
Adapter "iot" updated
host.rock Adapter "system.adapter.iot.0" is started
```

libvips ist in den aktuellen lts Versionen nicht in der geforderten Version libvips >= 8.9.1 enthalten.
Ich habe bereits jetzt auf buster debian geupgradet aber auch dort nicht. Es ist nur in der unstabl Version verfügbar. 

Es gibt wohl mehrere Personen die das Problem haben und libvips nur von iot benötigt wird.

Wie kann das Problem / Fehler beseitigt werden?

**Comment by detafun** [comment]
Hallo, hat hier einer weiter das Problem?
System ist Buster und in Buster gibt es  kein 8.9.1 von libvips

Hat jemand eine Lösung?

**Comment by Apollon77** [comment]
Es ist eine optionale Dependency und ausser das die Meldungen "nerven" ist erstmal alles ok ... keine AHnung ob wir eine Lösung finden die diese Warnungen unterdrückt

**Comment by detafun** [comment]
Wie steht es das libvips Paket selber bauen? Hast du das schon mal probiert?
Ich selber traue mich da nicht so direkt ran. Ohne Anleitung.

**Comment by GermanBluefox** [comment]
Das Packet ist nicht nötig im 99% der Fälle. Man muss nichts bauen, das ist nur die Meldung, dass optionales Paket fehlt
