### ISSUE TITLE
Verbindungszertifikate

### ISSUE THREAD

**Issue by Pocky2507** [ioBroker/ioBroker.iot#4]
Heute morgen war es mal wieder soweit.
Der iot Adapter stand als `Gelb´ im iobroker.
Bei neustart des Adapters kam dieser Log:

`
info: iot.0 starting. Version 0.1.3 in /opt/iobroker/node_modules/iobroker.iot, node: v8.12.0
2018-10-14 08:30:48.680  - info: iot.0 Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com with ""
2018-10-14 08:30:52.559  - error: iot.0 {}
2018-10-14 08:33:51.892  - info: host.raspberrypi object change system.adapter.iot.0
2018-10-14 08:33:51.892  - info: host.raspberrypi stopInstance system.adapter.iot.0
2018-10-14 08:33:51.893  - info: host.raspberrypi stopInstance system.adapter.iot.0 killing pid 20328
2018-10-14 08:33:51.934  - info: host.raspberrypi instance system.adapter.iot.0 terminated with code 0 (OK)
`
Erst nach klicken auf den Button:
ERHALTEN SIE NEUE Verbindungszertifikate
ging der Adapter auf Grün.
Ist es normal das hin und wieder neue Zertifikate geladen werden müssen?

**Comment by GermanBluefox** [comment]
Nein. Das ist nicht normal und ich biete dich beim nächsten mal zu prüfen ob die Objekte immer noch existieren und nicht lehr sind.
![image](https://user-images.githubusercontent.com/4582016/46915655-95d7b100-cfae-11e8-862f-59e16a954dee.png)

Kann es sein, dass du die editierst und dabei die kaputt gehen?

**Comment by Pocky2507** [comment]
Nein, da gehe ich nicht dran.
Ich werde das weiter beobachten und prüfe dann die Objekte.

**Comment by sigi2345** [comment]
Dieses Verhalten kann ich bestätigen!

**Comment by GermanBluefox** [comment]
> Dieses Verhalten kann ich bestätigen!
> 
> `
> 
> iot.0	2018-10-17 10:12:13.806	info	Request enums
> iot.0	2018-10-17 10:12:02.667	info	Request devices
> iot.0	2018-10-17 10:11:16.266	info	Connection lost
> iot.0	2018-10-17 10:11:16.266	info	Connection changed: disconnect
> iot.0	2018-10-17 10:11:16.217	info	Connection changed: connect
> iot.0	2018-10-17 10:11:14.992	info	Connection lost
> iot.0	2018-10-17 10:11:14.992	info	Connection changed: disconnect
> iot.0	2018-10-17 10:11:14.944	info	Connection changed: connect
> iot.0	2018-10-17 10:10:53.772	info	Connection lost
> iot.0	2018-10-17 10:10:53.772	info	Connection changed: disconnect
> iot.0	2018-10-17 10:10:53.725	info	Connection changed: connect
> iot.0	2018-10-17 10:10:52.502	info	Connection lost
> iot.0	2018-10-17 10:10:52.502	info	Connection changed: disconnect
> iot.0	2018-10-17 10:10:52.464	info	Connection changed: connect
> `

Ist Problem jetzt nach neuen Zertifikaten weg? 
Ich habe Logging erhöht. Bitte melden, wenn wieder das Problem da ist.

**Comment by sigi2345** [comment]
Wieder da..........
`

iot.0 | 2018-10-21 10:44:26.946 | info | Connection lost
-- | -- | -- | --
iot.0 | 2018-10-21 10:44:26.946 | info | Connection changed: disconnect
iot.0 | 2018-10-21 10:44:26.946 | debug | offline
iot.0 | 2018-10-21 10:44:26.905 | info | Connection changed: connect
iot.0 | 2018-10-21 10:44:26.693 | debug | reconnect
iot.0 | 2018-10-21 10:44:24.692 | info | Connection lost
iot.0 | 2018-10-21 10:44:24.692 | info | Connection changed: disconnect
iot.0 | 2018-10-21 10:44:24.692 | debug | offline
iot.0 | 2018-10-21 10:44:24.642 | info | Connection changed: connect
iot.0 | 2018-10-21 10:44:24.406 | debug | reconnect

`

**Comment by GermanBluefox** [comment]
iobroker.pro

**Comment by sigi2345** [comment]
Du meinst den APP Key?

**Comment by GermanBluefox** [comment]
Irgendwas, dass ich dich authentifizieren kann.
Am besten dein Login. Natürlich  ohne Password :)

вс, 21 окт. 2018 г. в 20:29, sigi2345 <notifications@github.com>:

**Comment by sigi2345** [comment]
Halo,
kommt immer wieder mal vor und der Adapter bleibt ziemlich lange auf Gelb.
Sollten unter Objekte (certs) nicht mehrere Datenfelder sein?

![screenshot 1036 _li](https://user-images.githubusercontent.com/41079106/47417231-d508bd80-d777-11e8-9e86-bba74817643a.jpg)


Sigi

**Comment by Pocky2507** [comment]
Hatte ich jetzt schon etwas länger nicht mehr.
Passwort im Adapter neu eingeben und speichern hat bei mir meistens geholfen.
Auch mal den Skill deaktivieren und wieder aktivieren kann nicht schaden.

**Comment by sigi2345** [comment]
`

2018-11-02 09:34:24.407 | error | {}
-- | -- | --
iot.0 | 2018-11-02 09:34:24.407 | error | Cannot fetch keys: "Internal server error"

`

**Comment by sigi2345** [comment]
Hallo,
habe jetzt ioBroker vom PI3 gelöscht.
Ist der Fehler immer noch? ( DUPLICATE_CLIENT_ID )

**Comment by GermanBluefox** [comment]
> Hallo,
> habe jetzt ioBroker vom PI3 gelöscht.
> Ist der Fehler immer noch? ( DUPLICATE_CLIENT_ID )

Sieht jetzt sauber aus. :)

**Comment by 69paulus** [comment]
Hallo, ich habe seid ein paar tagen genau dasselbe Problem, obwohl ich nichts geändert habe, bis vor ein paar tagen lief das ganze ohne Probleme, jetzt passiert mal immer wieder genau so wie beim Sigi2345. danke im voraus , viele Grüße

**Comment by mscDev24** [comment]
Hier leider auch das gleiche Problem. 

`Error by device connection: "getaddrinfo EAI_AGAIN a18wym7vjdl22g.iot.eu-west-1.amazonaws.com"`

Auf der Fritz den DNS-Server von "Internetanbieter zugewiesene DNSv4-Server" auf 1.1.1.1 und 8.8.8.8 geändert, keine "Linderung"

Die Instanz startet bei mir sauber und steigt dann nach gewisser Zeit aus. Die Buttons "Verbindungssicherheitszertifikate anfordern" sind übrigens nicht verfügbar -> Ghost.

ioBroker.pro Passwort habe ich auch schon geändert, wieder eingetragen. Mein Abo wurde gerade verlängert, vielleicht hat es damit was zu tun?

Im Browser gibt "a18wym7vjdl22g.iot.eu-west-1.amazonaws.com" auch keine Antwort, alles andere läuft wunderbar.

Kann hier jemand helfen?

**Comment by Apollon77** [comment]
Also ich kanns auflösen bei mir, es muss irgendwas lokales bei Dir mit DNS sein, Irgendetwas wie Pihole oder so im Einsatz?

**Comment by mscDev24** [comment]
Danke für die schnelle Antwort. Ich dachte jetzt mit einem Update auf NodeJS 20 wäre der Fehler vielleicht behoben, aber eben 2 Stunden verbrannt wieder auf die v18 zurückzukommen mit einem großen "glibcxx_3-4-26-Problem", egal...

Das Ursprungsproblem war eigentlich:

<img width="394" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/4a7a5085-422b-407c-adb7-3ab2950a0135">

Nach dem Upgrade...downgrade und dem Neustart...

<img width="569" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/03ad4398-87c2-4679-bad2-a8568c2b71e4">

...wäre die URL auch erreichbar. Ich beobachte mal, vielleicht bleibts ja jetzt stabil.

Wie geschrieben, meistens kommt nach einer noch unbekannten Zeit der Fehler.

Danke soweit...vielleicht hat es ja doch was gebracht,

**Comment by mscDev24** [comment]
Verrückt, es hat nicht lange gehalten:

<img width="579" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/3ff2a10c-8b7f-4dad-ac98-e8b3c0f09e01">


Das dumme ist nur: ich habe keinen Eintrag im Protokoll von IOT, obwohl die Instanz auf Debug Level steht und bei den erweiterten EInstellungen auch "debuggen" aktiv ist....

<img width="308" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/de2eb2ed-3a53-4d8e-8034-ddfbd9e3c520">

<img width="132" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/f499fbea-5f66-4ca6-9191-d0c7ada931c2">

**Comment by Apollon77** [comment]
Also wenn der Adapter crasht dann gibt es logs ... von iot oder vom js-controller

**Comment by mscDev24** [comment]
Leider besteht mein Problem noch immer, und natürlich hast du Recht was die Logs angeht.

<img width="625" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/209e92f3-2d0d-4ffb-ab10-d504d2ff2b5d">

```
2024-06-05 21:48:17.358  - [32minfo[39m: host.iobroker instance system.adapter.iot.0 started with pid 28313
2024-06-05 21:48:19.829  - [34mdebug[39m: iot.0 (28313) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-06-05 21:48:19.882  - [34mdebug[39m: iot.0 (28313) Objects client ready ... initialize now
2024-06-05 21:48:19.884  - [34mdebug[39m: iot.0 (28313) Objects create System PubSub Client
2024-06-05 21:48:19.885  - [34mdebug[39m: iot.0 (28313) Objects create User PubSub Client
2024-06-05 21:48:19.944  - [34mdebug[39m: iot.0 (28313) Objects client initialize lua scripts
2024-06-05 21:48:19.953  - [34mdebug[39m: iot.0 (28313) Objects connected to redis: 127.0.0.1:9001
2024-06-05 21:48:19.997  - [34mdebug[39m: iot.0 (28313) Redis States: Use Redis connection: 127.0.0.1:9000
2024-06-05 21:48:20.015  - [34mdebug[39m: iot.0 (28313) States create System PubSub Client
2024-06-05 21:48:20.017  - [34mdebug[39m: iot.0 (28313) States create User PubSub Client
2024-06-05 21:48:20.049  - [34mdebug[39m: iot.0 (28313) States connected to redis: 127.0.0.1:9000
2024-06-05 21:48:20.112  - [34mdebug[39m: iot.0 (28313) Plugin sentry Initialize Plugin (enabled=true)
2024-06-05 21:48:20.491  - [32minfo[39m: iot.0 (28313) starting. Version 3.2.2 in /opt/iobroker/node_modules/iobroker.iot, node: v18.20.3, js-controller: 5.0.19
2024-06-05 21:48:20.594  - [32minfo[39m: iot.0 (28313) Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
2024-06-05 21:48:21.129  - [34mdebug[39m: iot.0 (28313) [ALEXA] Name "Number of adapters to update" cannot be written and will be ignored
.
.
.
2024-06-05 21:48:21.142  - [34mdebug[39m: iot.0 (28313) [ALEXA] Name "Ready to use" cannot be written and will be ignored
2024-06-05 21:48:21.142  - [34mdebug[39m: iot.0 (28313) [ALEXA] Name "Battery level" cannot be written and will be ignored
2024-06-05 21:48:21.442  - [31merror[39m: iot.0 (28313) DNS name of a18wym7vjdl22g.iot.eu-west-1.amazonaws.com cannot be resolved: connection will be retried in 10 seconds.
2024-06-05 21:48:21.446  - [34mdebug[39m: iot.0 (28313) offline
2024-06-05 21:48:21.448  - [33mwarn[39m: iot.0 (28313) **Looks like your connection certificates are invalid. Please renew them via configuration dialog.**
2024-06-05 21:48:21.448  - [32minfo[39m: iot.0 (28313) Connection changed: disconnect
2024-06-05 21:48:21.449  - [34mdebug[39m: iot.0 (28313) [REMOTE] Cloud disconnected
2024-06-05 21:48:21.450  - [31merror[39m: iot.0 (28313) uncaught exception: Cannot convert undefined or null to object
2024-06-05 21:48:21.452  - [31merror[39m: iot.0 (28313) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29)
    at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22)
    at DeviceClient.emit (node:events:517:28)
    at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12)
    at MqttClient.emit (node:events:529:35)
    at TLSSocket.<anonymous> (/opt/iobroker/node_modules/mqtt/lib/client.js:360:10)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:657:7)
2024-06-05 21:48:21.453  - [31merror[39m: iot.0 (28313) Cannot convert undefined or null to object
2024-06-05 21:48:21.464  - [32minfo[39m: iot.0 (28313) terminating
2024-06-05 21:48:21.465  - [34mdebug[39m: iot.0 (28313) Plugin sentry destroyed
2024-06-05 21:48:21.466  - [33mwarn[39m: iot.0 (28313) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-05 21:48:21.474  - [34mdebug[39m: iot.0 (28313) [AlexaV3::DeviceManager]: (re)collecting devices...
2024-06-05 21:48:21.969  - [32minfo[39m: iot.0 (28313) terminating
.
.
.
2024-06-05 21:48:22.899  - [34mdebug[39m: iot.0 (28313) [AlexaV3::DeviceManager]: type detector found 48 controls
.
.
.
2024-06-05 21:48:22.938  - [34mdebug[39m: iot.0 (28313) [AlexaV3::DeviceManager]: finished collecting devices. there is/are 12 device(s) in total
.
.
.
2024-06-05 21:48:22.960  - [34mdebug[39m: iot.0 (28313) [AlexaV3::DeviceManager]: failed to subscribe for updates of 4 states
2024-06-05 21:48:22.962  - [31merror[39m: iot.0 (28313) Error in main: Error: DB closed
2024-06-05 21:48:23.046  - [31merror[39m: host.iobroker instance system.adapter.iot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-06-05 21:48:23.047  - [32minfo[39m: host.iobroker Restart adapter system.adapter.iot.0 because enabled
2024-06-05 21:48:23.047  - [33mwarn[39m: host.iobroker Do not restart adapter system.adapter.iot.0 because restart loop detected
```

Ich habe jetzt nochmal die Zertifikate erneuert, mal sehen wie lange es diesmal laufen mag.

**Comment by Apollon77** [comment]
But you did read the log, or? ;-))

> 2024-06-05 21:48:21.442  - �[31merror�[39m: iot.0 (28313) DNS name of a18wym7vjdl22g.iot.eu-west-1.amazonaws.com cannot be resolved: connection will be retried in 10 seconds.

check your DNS, maybe pihole or other adblockers on DNS level or such in place? try resolving manually ...

**Comment by mscDev24** [comment]
> PS: SOlution agsinst restartloop is to upgrade to v3.3.0 ... but in fact this will not change the DNS issue

Danke dafür. Ich bin noch auf der Suche nach dem DNS-Problem. Ich ziehe aus anderen Quellen in meinen eigenen Scripts auch noch Daten (RSS, Wetter, etc.) und da scheint es geklappt zu haben. Log war aber aus, aber error hätte ich geschrieben...

Die nächsten Stunden...Tage mal beobachten. 

pihole, adblocker meinst direkt auf dem Raspi? Hätte ich nicht aktiv eingeschalten. Wie kann ich das schauen? 

Ein ping auf die AWS klappt ja komischerweise mittlerweile....

**Comment by Apollon77** [comment]
> pihole, adblocker meinst direkt auf dem Raspi? Hätte ich nicht aktiv eingeschalten. Wie kann ich das schauen?

nein das sind wenn extra Dinge die du im netzwerk dir eingebaut hast. Wenn du davon nichts weisst ists also eher unwahrscheinlich

> Ein ping auf die AWS klappt ja komischerweise mittlerweile....

Dann kann er die Domain jetzt auflösen. vllt störung des ISP?

**Comment by mscDev24** [comment]
Gar kein schlechter Tipp mit der Störung. Ich hab mal das Fritz-Log angeschaut:

<img width="640" alt="image" src="https://github.com/ioBroker/ioBroker.iot/assets/66104061/1851bb88-f9ee-4f16-8bae-b9c9e3c03a70">

Und wahrscheinlich liegt hier der Hund begraben :)  Mein Funkkanal wird hier hin und hergeschubst und das passiert seit einer Woche fast jeden Abend um die gleiche Zeit.

Leider kann ich kein LAN an den Raspi hängen und hab jetzt mal einen manuellen Kanal für das 5GHz gewählt.

Danke!

**Comment by Apollon77** [comment]
Aber das sollte egal sein weil WLAN das an sich unter der haube managen sollte
