### ISSUE TITLE
uncaught exception: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.iot#467]
happend two times with adapter 1.12.1
don't know what was the trigger, maybe an iot device control by voice over iot skill
js-controller 4.0.23
nodejs 16.17.1
```
2022-09-30 07:41:39.735 - error: iot.0 (2193164) uncaught exception: Cannot read properties of undefined (reading 'name')
2022-09-30 07:41:39.735 - error: iot.0 (2193164) TypeError: Cannot read properties of undefined (reading 'name')
    at AlexaCustom.process (/opt/iobroker/node_modules/iobroker.iot/lib/alexaCustom.js:300:126)
    at processMessage (/opt/iobroker/node_modules/iobroker.iot/main.js:687:33)
    at DeviceClient.<anonymous> (/opt/iobroker/node_modules/iobroker.iot/main.js:887:17)
    at DeviceClient.emit (node:events:513:28)
    at DeviceClient.emit (node:domain:489:12)
    at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:826:12)
    at MqttClient.emit (node:events:513:28)
    at MqttClient.emit (node:domain:489:12)
    at MqttClient._handlePublish (/opt/iobroker/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:410:12)
2022-09-30 07:41:39.736 - error: iot.0 (2193164) Cannot read properties of undefined (reading 'name')
2022-09-30 07:41:39.750 - info: iot.0 (2193164) terminating
2022-09-30 07:41:39.751 - warn: iot.0 (2193164) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-09-30 07:41:39.814 - info: iot.0 (2193164) Connection changed: disconnect
2022-09-30 07:41:39.815 - info: iot.0 (2193164) Connection lost
2022-09-30 07:41:40.105 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'name')
2022-09-30 07:41:40.109 - error: host.iobroker Caught by controller[0]:     at AlexaCustom.process (/opt/iobroker/node_modules/iobroker.iot/lib/alexaCustom.js:300:126)
2022-09-30 07:41:40.109 - error: host.iobroker Caught by controller[0]:     at processMessage (/opt/iobroker/node_modules/iobroker.iot/main.js:687:33)
2022-09-30 07:41:40.109 - error: host.iobroker Caught by controller[0]:     at DeviceClient.<anonymous> (/opt/iobroker/node_modules/iobroker.iot/main.js:887:17)
2022-09-30 07:41:40.109 - error: host.iobroker Caught by controller[0]:     at DeviceClient.emit (node:events:513:28)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at DeviceClient.emit (node:domain:489:12)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:826:12)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at MqttClient.emit (node:events:513:28)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at MqttClient.emit (node:domain:489:12)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at MqttClient._handlePublish (/opt/iobroker/node_modules/mqtt/lib/client.js:1277:12)
2022-09-30 07:41:40.110 - error: host.iobroker Caught by controller[0]:     at MqttClient._handlePacket (/opt/iobroker/node_modules/mqtt/lib/client.js:410:12)
2022-09-30 07:41:40.110 - error: host.iobroker instance system.adapter.iot.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-09-30 07:42:11.969 - info: iot.0 (2288952) starting. Version 1.12.1 in /opt/iobroker/node_modules/iobroker.iot, node: v16.17.1, js-controller: 4.0.23
2022-09-30 07:42:12.026 - info: iot.0 (2288952) Connecting with ???.iot.eu-west-1.amazonaws.com
2022-09-30 07:42:12.779 - info: iot.0 (2288952) Connection changed: connect

```

**Comment by Diginix** [comment]
today it happend without any interaction at this time as far as i can remember

**Comment by Apollon77** [comment]
will be fixed in next release
