### ISSUE TITLE
Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.iot#62]
```
2019-09-11 03:12:35.240  - [31merror[39m: iot.0 uncaught exception: Cannot read property 'message' of undefined
2019-09-11 03:12:35.241  - [31merror[39m: iot.0 TypeError: Cannot read property 'message' of undefined
2019-09-11 03:12:35.279  - [31merror[39m: Caught by controller[0]: TypeError: Cannot read property 'message' of undefined
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1713:102)
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:198:13)
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:198:13)
2019-09-11 03:12:35.280  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
2019-09-11 03:12:35.281  - [31merror[39m: Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
2019-09-11 03:12:35.281  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
2019-09-11 03:12:35.281  - [31merror[39m: Caught by controller[0]:     at endReadableNT (_stream_readable.js:1145:12)
2019-09-11 03:12:35.281  - [31merror[39m: Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-09-11 03:12:35.281  - [31merror[39m: host.iobroker instance system.adapter.iot.0 terminated with code 0 (OK)
2019-09-11 03:12:35.281  - [32minfo[39m: host.iobroker Restart adapter system.adapter.iot.0 because enabled
2019-09-11 03:13:05.297  - [32minfo[39m: host.iobroker instance system.adapter.iot.0 started with pid 28192
2019-09-11 03:13:06.646  - [32minfo[39m: iot.0 starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.iot, node: v10.16.3
2019-09-11 03:13:06.681  - [32minfo[39m: iot.0 Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
2019-09-11 03:13:07.229  - [32minfo[39m: iot.0 shelly.0.SHSW-1#xxx#1.Relay0.Switch is auto added with type  light.
2019-09-11 03:13:07.236  - [32minfo[39m: iot.0 shelly.0.SHSW-1#yyy#1.Relay0.Switch is auto added with type  light.
2019-09-11 03:13:07.241  - [32minfo[39m: iot.0 sonoff.0.Nachtlicht Benchy.POWER is auto added with type  light.
2019-09-11 03:13:07.246  - [32minfo[39m: iot.0 sonoff.0.Nachtlicht Liah.POWER is auto added with type  light.
2019-09-11 03:13:07.250  - [32minfo[39m: iot.0 sonoff.0.Nachtlicht Marcus.POWER is auto added with type  light.
2019-09-11 03:13:07.255  - [32minfo[39m: iot.0 sonoff.0.Stehlampe.POWER is auto added with type  light.
2019-09-11 03:13:07.259  - [32minfo[39m: iot.0 shelly.0.SHSW-1#zzz#1.Relay0.Switch is auto added with type  light.
2019-09-11 03:13:07.288  - [32minfo[39m: iot.0 shelly.0.SHRGBW2#rrr#1.color is auto added with type  rgb.
2019-09-11 03:13:07.294  - [32minfo[39m: iot.0 sonoff.0.Schreibtischlampe.POWER is auto added with type  light.
2019-09-11 03:13:07.298  - [32minfo[39m: iot.0 sonoff.0.Küchenlicht.POWER is auto added with type  light.
2019-09-11 03:13:07.303  - [32minfo[39m: iot.0 sonoff.0.TV Steckdose.POWER is auto added with type  socket.
2019-09-11 03:13:07.310  - [32minfo[39m: iot.0 tuya.0.edrertetetert2d5a02cc.1 is auto added with type  socket.
2019-09-11 03:13:07.313  - [32minfo[39m: iot.0 javascript.0.scriptEnabled.Steckdosen.Schreibtischsteckdosen_Automatik is auto added with type  socket.
2019-09-11 03:13:07.322  - [32minfo[39m: iot.0 Cannot auto convert chromecast.0.Küche.status.volume. Type volume is not available, yet. If you need the state please add him manually
2019-09-11 03:13:07.326  - [32minfo[39m: iot.0 Cannot auto convert chromecast.0.Schlafzimmer.status.volume. Type volume is not available, yet. If you need the state please add him manually
2019-09-11 03:13:07.330  - [32minfo[39m: iot.0 Cannot auto convert chromecast.0.WohnzimmerJBL.status.volume. Type volume is not available, yet. If you need the state please add him manually
2019-09-11 03:13:07.715  - [32minfo[39m: iot.0 Connection changed: connect
```

**Comment by TA2k** [comment]
fixed with PR #61
