### ISSUE TITLE
Caught by controller[0]: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.iot#758]
Every Night or with restart of the iot adapter i get this error. cant remember to have changed anything special and cant identify the source of this error. 

**Describe the bug**  
`<html>
<body>

host.iobroker | 2024-05-05 06:44:00.462 | info | instance system.adapter.iot.0 started with pid 301447
-- | -- | -- | --
host.iobroker | 2024-05-05 06:43:57.774 | info | instance system.adapter.iot.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at TLSSocket.emit (node:events:529:35)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at TLSSocket.<anonymous> (/opt/iobroker/node_modules/mqtt/lib/client.js:360:10)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at MqttClient.emit (node:domain:489:12)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at MqttClient.emit (node:events:529:35)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at DeviceClient.emit (node:domain:489:12)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at DeviceClient.emit (node:events:517:28)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29)
host.iobroker | 2024-05-05 06:43:57.774 | error | Caught by controller[0]: at Function.keys (<anonymous>)
host.iobroker | 2024-05-05 06:43:57.773 | error | Caught by controller[0]: TypeError: Cannot convert undefined or null to object
iot.0 | 2024-05-05 06:43:57.469 | error | Cannot convert undefined or null to object
iot.0 | 2024-05-05 06:43:57.469 | error | TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29) at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22) at DeviceClient.emit (node:events:517:28) at DeviceClient.emit (node:domain:489:12) at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12) at MqttClient.emit (node:events:529:35) at MqttClient.emit (node:domain:489:12) at TLSSocket.<anonymous> (/opt/iobroker/node_modules/mqtt/lib/client.js:360:10) at TLSSocket.emit (node:events:529:35)
iot.0 | 2024-05-05 06:43:57.468 | error | uncaught exception: Cannot convert undefined or null to object
iot.0 | 2024-05-05 06:43:57.464 | info | Connection lost
iot.0 | 2024-05-05 06:43:57.464 | info | Connection changed: disconnect
host.iobroker | 2024-05-05 06:43:57.433 | info | stopInstance system.adapter.iot.0 send kill signal
iot.0 | 2024-05-05 06:43:57.397 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
iot.0 | 2024-05-05 06:43:57.396 | info | terminating
iot.0 | 2024-05-05 06:43:57.393 | info | Got terminate signal TERMINATE_YOURSELF
`
Plattform: linux
RAM: 7.8 GB
Node.js: v18.20.2
NPM: 10.5.0
JS Controller: 
5.0.19
`Plattform:
linux
Betriebssystem:
linux
Architektur:
arm64
CPUs:
4
Geschwindigkeit:
2400 MHz
Modell:
Cortex-A76

**Comment by tseroo** [comment]
Same issue here...  
`2024-05-04 03:29:22.566 - debug: iot.0 (24008) offline
2024-05-04 03:29:22.568 - info: iot.0 (24008) Connection changed: disconnect
2024-05-04 03:29:22.569 - debug: iot.0 (24008) [REMOTE] Cloud disconnected
2024-05-04 03:29:22.574 - error: iot.0 (24008) uncaught exception: Cannot convert undefined or null to object
2024-05-04 03:29:22.575 - error: iot.0 (24008) TypeError: Cannot convert undefined or null to object
at Function.keys ()
at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29)
at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22)
at DeviceClient.emit (node:events:517:28)
at DeviceClient.emit (node:domain:489:12)
at MqttClient. (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12)
at MqttClient.emit (node:events:529:35)
at MqttClient.emit (node:domain:489:12)
at TLSSocket. (/opt/iobroker/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:360:10)
at TLSSocket.emit (node:events:529:35)
2024-05-04 03:29:22.575 - error: iot.0 (24008) Cannot convert undefined or null to object
2024-05-04 03:29:22.592 - info: iot.0 (24008) terminating
2024-05-04 03:29:22.593 - debug: iot.0 (24008) Plugin sentry destroyed
2024-05-04 03:29:22.593 - warn: iot.0 (24008) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-05-04 03:29:23.095 - info: iot.0 (24008) terminating
2024-05-04 03:29:33.953 - error: host.iobroker Caught by controller[0]: TypeError: Cannot convert undefined or null to object
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at Function.keys ()
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at DeviceClient.emit (node:events:517:28)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at DeviceClient.emit (node:domain:489:12)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at MqttClient. (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at MqttClient.emit (node:events:529:35)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at MqttClient.emit (node:domain:489:12)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at TLSSocket. (/opt/iobroker/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:360:10)
2024-05-04 03:29:33.954 - error: host.iobroker Caught by controller[0]: at TLSSocket.emit (node:events:529:35)
2024-05-04 03:29:33.954 - error: host.iobroker instance system.adapter.iot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-05-04 03:29:33.954 - info: host.iobroker Restart adapter system.adapter.iot.0 because enabled
2024-05-04 03:30:04.163 - info: host.iobroker instance system.adapter.iot.0 started with pid 24105`

Plattform  docker
Betriebssystem  linux
Architektur  x64
CPUs  4
Geschwindigkeit 2399 MHz
Modell  Intel Core Processor (Skylake, IBRS)
RAM  13.54 GB
Node.js  v18.20.2
NPM  10.5.0

**Comment by Menne01** [comment]
Kann ich auch bestätigen.

**Comment by arteck** [comment]
hier auch
![grafik](https://github.com/ioBroker/ioBroker.iot/assets/6681528/1b5e8901-b15c-4c35-a938-6f95951c6b4d)

**Comment by superemil70** [comment]
Bei mir auch seit ein paar Tagen. Immer nur nach einem Neustart
`2024-05-08 08:28:00.067	error	Cannot convert undefined or null to object
iot.0
	2024-05-08 08:28:00.066	error	TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29) at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22) at DeviceClient.emit (node:events:517:28) at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12) at MqttClient.emit (node:events:529:35) at TLSSocket.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:360:10) at TLSSocket.emit (node:events:529:35) at node:net:350:12 at TCP.done (node:_tls_wrap:657:7)
iot.0
	2024-05-08 08:28:00.064	error	uncaught exception: Cannot convert undefined or null to object
iot.0
	2024-05-08 08:27:00.061	error	Cannot convert undefined or null to object
iot.0
	2024-05-08 08:27:00.061	error	TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29) at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22) at DeviceClient.emit (node:events:517:28) at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12) at MqttClient.emit (node:events:529:35) at TLSSocket.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:360:10) at TLSSocket.emit (node:events:529:35) at node:net:350:12 at TCP.done (node:_tls_wrap:657:7)
iot.0
	2024-05-08 08:27:00.058	error	uncaught exception: Cannot convert undefined or null to object`

System
`
    Plattform: docker (official image - v9.1.1)
    Betriebssystem: linux
    Architektur: x64
    CPUs: 4
    Geschwindigkeit: 1501 MHz
    Modell: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
    RAM: 11.5 GB
    System-Betriebszeit: 43 T. 17:39:52
    Node.js: v18.19.0
    time: 1715153126234
    timeOffset: -120
    NPM: 10.2.3
    Adapter-Anzahl: 539
    Datenträgergröße: 3572.6 GB
    Freier Festplattenspeicher: 2111.0 GB
    Aktive Instanzen: 29
    Pfad: /opt/iobroker/
    Betriebszeit: 43 T. 17:29:22
    aktiv: 
`

**Comment by Apollon77** [comment]
Please try 3.3.0

**Comment by blackeagle998** [comment]
> Please try 3.3.0

Heute auf Version 3.3.0 geupdated und bekomme weiterhin die Meldung:
![image](https://github.com/ioBroker/ioBroker.iot/assets/58532773/5ae0dd13-2d04-4cf8-a304-f5ab30da4ad7)

**Comment by Menne01** [comment]
Ich habe keine Probleme damit.
An deiner Stelle ich mal das System auf den aktuellen Stand bringen.

Aktuell ist:

Node.js 18.20.2
Npm 10.7.0

**Comment by blackeagle998** [comment]
> Ich habe keine Probleme damit. An deiner Stelle würde ich mal das System auf den aktuellen Stand bringen.
> 
> Aktuell ist:
> 
> Node.js 18.20.2 Npm 10.7.0

Habe mein System entsprechend geupdated, jetzt funktioniert es ohne Fehlermeldung.
Danke für den Hinweis!
