### ISSUE TITLE
Type error(s)

### ISSUE THREAD

**Issue by sammie76-2** [ioBroker/ioBroker.iot#764]
**Describe the bug**  
I get error messages in the ioBroker protocol.

_Cannot convert undefined or null to object_

_TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at RemoteAccess.onCloudDisconnect (/opt/iobroker/node_modules/iobroker.iot/lib/remote.js:720:29) at DeviceClient.onDisconnect (/opt/iobroker/node_modules/iobroker.iot/main.js:564:22) at DeviceClient.emit (node:events:517:28) at DeviceClient.emit (node:domain:489:12) at MqttClient.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/device/index.js:797:12) at MqttClient.emit (node:events:529:35) at MqttClient.emit (node:domain:489:12) at TLSSocket.<anonymous> (/opt/iobroker/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:360:10) at TLSSocket.emit (node:events:529:35)_

_uncaught exception: Cannot convert undefined or null to object_

Sometimes there is also an warning:

_Terminated (UNCAUGHT_EXCEPTION): Without reason_

The adapter restarts very often every day.

I am using version 3.2.2 of the iot adapter.

**Comment by sammie76-2** [comment]
Updating nodejs to 20.x solved the problem.
